<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
echo '<title>Zoo</title>';
echo '<script src="script.js" defer></script>';
echo '<script src="serviceworker.js" defer></script>';
echo '<link rel="stylesheet" href="index.css">';
echo '</head>';
echo '<script>';
echo '';
echo '</script>';
echo '<body id="zoo">';
echo '';
echo '<div contenteditable="false" class="zooField">';
echo '<h1 id="Zooname" label for="name" class="title">World Zoo</h1>';
echo '<div class="zooInfo">';
echo '<p id="Zoocapacity" label for="capacity">Capacity:250</p>';
echo '<p id="numberofanimals" label for="animalNumber">Number of animals:4</p>';
echo '<p id="numberofguest" label for="guestNumber">Number of guest:57</p>';
echo '<button id="myBtn">Add Guest</button>';
echo '<my-counter></my-counter>';
echo '<script src="GuestAdd.js"></script>';
echo '<button id="addAnimal">Add Animal</button>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="animalInfo">';
echo '<h2 id="animals">';
echo '<h1 id="Animallist" class="title">Animals: </h1>';
echo '<!--Added a animal list with a find by name function and on key up event handler-->';
echo '<ul id="animalList">';
echo '</h2>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<table>';
echo '<tr>';
echo '<th>Animal</th>';
echo '<th>Name</th>';
echo '<th>Age</th>';
echo '<th>Gender</th>';
echo '<th>Weight</th>';
echo '<th>IsPregnant</th>';
echo '</tr>';
echo '<tr>';
echo '<td>Platypus</td>';
echo '<td>Perry</td>';
echo '<td>2</td>';
echo '<td>Female</td>';
echo '<td>3.2</td>';
echo '<td>True</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Hummingbird</td>';
echo '<td>Harry</td>';
echo '<td>2</td>';
echo '<td>Male</td>';
echo '<td>3.2</td>';
echo '<td>False</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Shark</td>';
echo '<td>Sherry</td>';
echo '<td>2</td>';
echo '<td>Female</td>';
echo '<td>852</td>';
echo '<td>True</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Chimpanzee</td>';
echo '<td>Cherry</td>';
echo '<td>2</td>';
echo '<td>Female</td>';
echo '<td>3.2</td>';
echo '<td>True</td>';
echo '</tr>';
echo '';
echo '</table>';
echo '';
echo '';
echo '';
echo '<div id="submit">';
echo '<!--Created both an animal and guest submit form-->';
echo '<form action=""  onsubmit="guestSubmit()">';
echo '<fieldset>';
echo '<p>Guest submit</p>';
echo '<Label for="first name">first name';
echo '<input type = "text" id= "first name">';
echo '</Label><br>';
echo '<Label for="last name">last name';
echo '<input type = "text" id= "last name">';
echo '</Label><br>';
echo '<Label for="phone">phone number';
echo '<input type = "text" id= "phone">';
echo '</Label><br>';
echo '<input type="submit" value="Submit" id="guestButton">';
echo '</fieldset>';
echo '</form>';
echo '';
echo '<form action=""  onsubmit="addAnimals()">';
echo '<label for="type">Type:';
echo '<select Name="Animal_listbox" Size="Number_of_options" id="Animal_listbox"  onChange='Choice();'>';
echo '<option></option>';
echo '<option value="1"> Platypus </option>';
echo '<option value="2"> Hummingbird </option>';
echo '<option value="3"> Chimpanzee </option>';
echo '<option value="4"> Shark </option>';
echo '</select>';
echo '</label><br><br>';
echo '<fieldset id= "animalsubmit">';
echo '<p>Add an animal</p>';
echo '<label for="type2">Type:';
echo '<input type="text" id="type2" name="type2" value="">';
echo '</label><br><br>';
echo '<label for="animalname">Name:';
echo '<input type="text" id="animalname" name="animalname" value="">';
echo '</label><br><br>';
echo '<label for="age">Age:';
echo '<input type="number" id="age" name="age" value="">';
echo '</label><br><br>';
echo '<label>Gender:';
echo '<input type="text" name="gender" id="gender" value="">';
echo '</label><br><br>';
echo '<label for="name">Weight:';
echo '<input type="text" id="weight" name="weight" value="">';
echo '</label><br><br>';
echo '<label>Is Pregnant?:';
echo '<input type="text" name="pregnant" id="pregnant" value="">';
echo '</label><br>';
echo '<input type="submit" value="Submit">';
echo '<div>';
echo '<ul id="listcontent"></ul>';
echo '</div>';
echo '</fieldset>';
echo '</form>';
echo '</body>';
echo '</html>';
?>
